# ~/.config/alacritty/alacritty.toml
# https://alacritty.org/config-alacritty.html

[window]
blur = false
opacity = 0.85
title = "Alacritty"
decorations = "none"
dynamic_title = true
dynamic_padding = true

[terminal]
[terminal.shell]
args = ["--login"]
program = "/usr/bin/fish"

[general]
working_directory = "None"
live_config_reload = true

[font]
size = 11.50
builtin_box_drawing = true
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[font.normal]
style = "Bold"
family = "Intel One Mono"

[font.bold]
style = "Bold"

[font.italic]
style = "Bold Italic"

[font.bold_italic]
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"
foreground = "#eaeaea"

[colors.normal]
black = "#000000"
blue = "#41b2f7"
cyan = "#32f8f4"
green = "#32f891"
magenta = "#f54bf9"
red = "#f94a4f"
white = "#eaeaea"
yellow = "#faf76e"

[colors.bright]
black = "#444444"
blue = "#41b2f7"
cyan = "#32f8f4"
green = "#32f891"
magenta = "#f54bf9"
red = "#f7191f"
white = "#ffffff"
yellow = "#f9f655"

# [terminal]

# [terminal.shell]
# args = ["--login"]
# program = "/bin/bash"

# [terminal.shell]
# program = "pwsh"

# [terminal.shell]
# args = ["-d Arch", "-u wrx"]
# program = "C:\Windows\System32\wsl.exe"

# # fix pwsh numpad enter
# [keyboard]
# [[keyboard.bindings]]
# key = "NumpadEnter"
# mods = "None"
# action = "ReceiveChar"
