xcopy .aliases %UserProfile%
xcopy .bash_profile %UserProfile%
xcopy .bash_prompt %UserProfile%
xcopy .bashrc %UserProfile%
xcopy .editorconfig %UserProfile%
xcopy .gitattributes %UserProfile%
xcopy .gitconfig %UserProfile%
xcopy .gvimrc %UserProfile%
xcopy .vimrc %UserProfile%
