# Helix
# ------------------------------------------

theme = "catppuccin_mocha"

# Editor
# ------------------------------------------

[editor]
rulers = []
text-width = 256
true-color = true
color-modes = true
cursorline = true
bufferline = "always"
line-number = "relative"
default-line-ending	= "lf"
insert-final-newline = true
popup-border = "all"
auto-completion	= true
completion-replace = false
completion-trigger-len = 1
preview-completion-insert = true

[editor.statusline]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select	= "SELECT"
left = [ "mode", "file-name", "read-only-indicator", "file-modification-indicator", "spinner" ]
right = [ "register", "selections", "file-type", "file-encoding", "file-line-ending", "position", "position-percentage", "spacer", "diagnostics" ]
center = [ "version-control" ]

[editor.lsp]
enable = true
snippets = true
display-messages = true
auto-signature-help	= true
display-inlay-hints	= false
display-signature-help-docs = true
goto-reference-include-declaration = true

[editor.file-picker]
ignore = true
hidden = false

[editor.search]
smart-case = true
wrap-around = true

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 0

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
tab = "→"
space = " "
tabpad = " "
newline = " "

[editor.gutters]
layout = [ "diagnostics", "spacer", "line-numbers", "spacer", "diff" ]

# Keymaps Insert
# ------------------------------------------

[keys.insert]
esc = [ "collapse_selection", "normal_mode" ]

# Keymaps Normal
# ------------------------------------------

[keys.normal]
"$" = "goto_line_end"
"0" = "goto_line_start"
"G" = "goto_file_end"
"M" = "match_brackets"
"X" = "select_line_above"
"V" = [ "select_mode", "extend_to_line_bounds" ]
"D" = [ "extend_to_line_end", "delete_selection" ]
"esc" = [ "collapse_selection", "keep_primary_selection" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
"A-j" = [ "extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before" ]
"A-m" = [ "keep_primary_selection", "move_prev_word_start", "move_next_word_end", "search_selection", "select_mode" ]


[keys.normal.space]
"q" = [ ":buffer-close" ]
"Q" = [ ":buffer-close!" ]

# Keymaps Select
# ------------------------------------------

[keys.select]
"$" = "goto_line_end"
"0" = "goto_line_start"
"G" = "goto_file_end"
"M" = "match_brackets"
"X" = "select_line_above"
"D" = [ "extend_to_line_end", "delete_selection", "normal_mode" ]
"u" = [ "switch_to_lowercase", "collapse_selection", "normal_mode" ]
"U" = [ "switch_to_uppercase", "collapse_selection", "normal_mode" ]
"esc" = [ "collapse_selection", "keep_primary_selection", "normal_mode" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "keep_primary_selection", "select_mode" ]
"A-j" = [ "extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before", "keep_primary_selection", "select_mode" ]
"A-m" = [ "search_selection", "extend_search_next" ]
