# https://github.com/jesseduffield/lazygit/issues/4258
# https://github.com/jesseduffield/lazygit/issues/5136
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  tabWidth: 2
  scrollHeight: 4
  scrollOffMargin: 4
  expandFocusedSidePanel: true
  shortTimeFormat: 15:04
  showRandomTip: true
  showCommandLog: true
  showNumstatInFilesView: true
  nerdFontsVersion: "3"
  useHunkModeInStagingView: true
keybinding:
  universal:
    quit: [ q, <ctrl+q> ]
    suspendApp: <disabled>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: [ <up>, k ]
    nextItem: [ <down>, j ]
    prevPage: ","
    nextPage: "."
    scrollLeft: H
    scrollRight: L
    gotoTop: [ "<", <home> ]
    gotoBottom: [ ">", <end> ]
    toggleRangeSelect: v
    rangeSelectDown: <shift+down>
    rangeSelectUp: <shift+up>
    prevBlock: [ <left>, h, <backtab> ]
    nextBlock: [ <right>, l, <tab> ]
    jumpToBlock:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    focusMainView: "0"
    nextMatch: "n"
    prevMatch: "N"
    startSearch: /
    moveWordLeft: <ctrl+left>
    moveWordRight: <ctrl+right>
    backspaceWord: <ctrl+backspace>
    forwardDeleteWord: <ctrl+delete>
    optionMenu: "?"
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirmMenu: <enter>
    confirmSuggestion: <enter>
    confirmInEditor: [ <alt+enter>, <ctrl+s> ]
    remove: d
    new: "n"
    newWorktree: w
    edit: e
    openFile: o
    scrollUpMain: [ <pgup>, K, <ctrl+u> ]
    scrollDownMain: [ <pgdown>, J, <ctrl+d> ]
    executeShellCommand: ":"
    createRebaseOptionsMenu: m
    pushFiles: <alt+shift+p>
    pullFiles: <alt+p>
    refresh: R
    createPatchOptionsMenu: <f12>
    nextTab: "]"
    prevTab: "["
    nextScreenMode: +
    prevScreenMode: _
    cycleDiffRenderers: "|"
    undo: z
    redo: Z
    filteringMenu: <ctrl+s>
    diffingMenu: [ W, <ctrl+e> ]
    copyToClipboard: <ctrl+y>
    openRecentRepos: <ctrl+r>
    submitEditorText: <enter>
    extrasMenu: "@"
    toggleWhitespaceInDiffView: <ctrl+w>
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
    increaseRenameSimilarityThreshold: )
    decreaseRenameSimilarityThreshold: (
    openDiffTool: <ctrl+t>
    editConfig: <alt+shift+c>
git:
  diffRenderers:
    # - pager: "" # default
    - command: delta --paging=never --tabs=2 --no-gitconfig
    - command: delta --paging=never --tabs=2 --side-by-side --no-gitconfig
