# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  tabWidth: 2
  scrollHeight: 3
  scrollOffMargin: 3
  expandFocusedSidePanel: true
  shortTimeFormat: 15:04
  showRandomTip: true
  showCommandLog: true
  showNumstatInFilesView: true
  nerdFontsVersion: "3"
  useHunkModeInStagingView: true
keybinding:
  universal:
    quit: q
    quit-alt1: <c-q>
    cyclePagers: "|"
git:
  pagers:
    # - pager: "" # default
    - pager: delta --paging=never --navigate --tabs=2 --no-gitconfig
    - pager: delta --paging=never --navigate --tabs=2 --side-by-side --no-gitconfig
