preload = /usr/share/hypr/wall2.png
wallpaper = , /usr/share/hypr/wall2.png

# preload = /home/lambda/dev/open-sos/Wallpaper-Bank/wallpapers/Fantasy-Snow-Valley.png
# wallpaper = , /home/lambda/dev/open-sos/Wallpaper-Bank/wallpapers/Fantasy-Snow-Valley.png
