# ~/.config/mpv/mpv.conf

volume=80

osd-font-size=14
osd-font="JetBrains Mono Bold"

script-opts=osc-font="JetBrains Mono Bold"
script-opts=osc-scalewindowed=0.44,osc-scalefullscreen=0.44

sub-margin-y=100
sub-font-size=33
sub-font="JetBrains Mono SemiBold"

# subs at bottom
sub-ass-override=force

# Do not close the window on exit
keep-open=yes
