# ------------------------------------------
# Intel One Mono for linux
# ------------------------------------------

[font]
size = 11.25
allow_float_size = true

[[font.normal]]
style = "Bold"
family = "Intel One Mono"

[[font.bold]]
style = "Bold"

[[font.italic]]
slant = "Italic"
style = "Bold Italic"

[[font.bold_italic]]
slant = "Italic"
style = "Bold Italic"

# ------------------------------------------
# JetBrains Mono NL
# set size = 10.25 for JBM windows
# set linespace = 2 for JBM for windows
# ------------------------------------------

[[font.normal]]
style = "ExtraBold"
family = "JetBrains Mono NL"

[[font.bold]]
style = "ExtraBold"

[[font.italic]]
slant = "Italic"
style = "ExtraBold Italic"

[[font.bold_italic]]
slant = "Italic"
style = "ExtraBold Italic"
