# ------------------------------------------
# Intel One Mono
# set size = 10.25 for windows
# set linespace = 1 (linux), 2 (windows)
# ------------------------------------------

[font]
size = 11.25
hinting = "full"
edging = "antialias"
allow_float_size = true

[[font.normal]]
style = "Bold"
family = "Intel One Mono"

[[font.bold]]
style = "Bold"
family = "Intel One Mono"

[[font.italic]]
style = "Bold Italic"
family = "Intel One Mono"

[[font.bold_italic]]
style = "Bold Italic"
family = "Intel One Mono"

# ------------------------------------------
# JetBrains Mono NL
# set size = 10.25 for JBM windows
# set linespace = 3 (linux), 2 (windows)
# ------------------------------------------

# [font]
# size = 10.75
# hinting = "full"
# edging = "antialias"
# allow_float_size = true
#
# [[font.normal]]
# style = "ExtraBold"
# family = "JetBrains Mono NL"
#
# [[font.bold]]
# style = "ExtraBold"
# family = "JetBrains Mono NL"
#
# [[font.italic]]
# style = "ExtraBold Italic"
# family = "JetBrains Mono NL"
#
# [[font.bold_italic]]
# style = "ExtraBold Italic"
# family = "JetBrains Mono NL"
