# ------------------------------------------
# Intel One Mono
# ------------------------------------------

[font]
size = 15.15
allow_float_size = true

[[font.normal]]
style = "Bold"
family = "Intel One Mono"

[[font.bold]]
style = "Bold"

[[font.italic]]
slant = "Italic"
style = "Bold Italic"

[[font.bold_italic]]
slant = "Italic"
style = "Bold Italic"

# ------------------------------------------
# JetBrains Mono NL
# set linespace = 1 for JBM
# ------------------------------------------

# [font] # -> linux
# size = 15.00
# allow_float_size = true

# [font] # -> windows
# size = 14.00
# allow_float_size = false

[[font.normal]]
style = "ExtraBold"
family = "JetBrains Mono NL"

[[font.bold]]
style = "ExtraBold"

[[font.italic]]
slant = "Italic"
style = "ExtraBold Italic"

[[font.bold_italic]]
slant = "Italic"
style = "ExtraBold Italic"
